[package]
name = "nexfsck-journal"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nexfsck-core = { path = "../nexfsck-core" }
nexfsck-io = { path = "../nexfsck-io" }
zerocopy.workspace = true
thiserror.workspace = true
tracing.workspace = true
